# Generated by Django 5.2.14 on 2026-05-18 11:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gabinete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('vereador', models.CharField(max_length=150)),
                ('email_responsavel', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('status_licenca', models.CharField(choices=[('ativa', 'Ativa'), ('teste', 'Teste'), ('suspensa', 'Suspensa'), ('expirada', 'Expirada')], default='teste', max_length=20)),
                ('inicio_licenca', models.DateField(default=django.utils.timezone.localdate)),
                ('fim_licenca', models.DateField(blank=True, null=True)),
                ('valor_mensal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('limite_usuarios', models.PositiveIntegerField(default=5)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
