# Generated by Django 5.2.14 on 2026-05-19 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vencimento', models.DateField()),
                ('pago_em', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('paga', 'Paga'), ('atrasada', 'Atrasada'), ('cancelada', 'Cancelada')], default='aberta', max_length=20)),
                ('metodo_pagamento', models.CharField(choices=[('pix', 'PIX'), ('boleto', 'Boleto'), ('cartao', 'Cartao'), ('transferencia', 'Transferencia'), ('manual', 'Manual')], default='pix', max_length=20)),
                ('codigo_pagamento', models.CharField(blank=True, max_length=255)),
                ('gateway', models.CharField(blank=True, max_length=50)),
                ('gateway_payment_id', models.CharField(blank=True, max_length=120)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('gabinete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobrancas', to='assinaturas.gabinete')),
            ],
            options={
                'ordering': ['-vencimento'],
            },
        ),
    ]
