# Generated by Django 5.2.14 on 2026-05-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0002_cobranca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gabinete',
            name='status_licenca',
            field=models.CharField(choices=[('ativa', 'Ativa'), ('teste', 'Teste'), ('suspensa', 'Suspensa'), ('expirada', 'Expirada')], default='suspensa', max_length=20),
        ),
    ]
