# Generated by Django 5.2.14 on 2026-05-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0003_alter_gabinete_status_licenca'),
    ]

    operations = [
        migrations.AddField(
            model_name='gabinete',
            name='assinatura_cargo',
            field=models.CharField(default='Vereador', max_length=80),
        ),
        migrations.AddField(
            model_name='gabinete',
            name='assinatura_nome',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='gabinete',
            name='assuntos_padrao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gabinete',
            name='dias_prazo_padrao',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='gabinete',
            name='logo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='gabinete',
            name='secretarias_padrao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gabinete',
            name='template_oficio',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='gabinete',
            index=models.Index(fields=['status_licenca'], name='assinaturas_status__67f400_idx'),
        ),
        migrations.AddIndex(
            model_name='gabinete',
            index=models.Index(fields=['fim_licenca'], name='assinaturas_fim_lic_38a54f_idx'),
        ),
        migrations.AddIndex(
            model_name='gabinete',
            index=models.Index(fields=['criado_em'], name='assinaturas_criado__4f739f_idx'),
        ),
    ]
