# Generated by Django 5.2.14 on 2026-05-22 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0007_atendimento_ativo_atendimento_excluido_em_and_more'),
        ('encaminhamentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='encaminhamento',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='encaminhamento',
            name='excluido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encaminhamento',
            name='excluido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encaminhamentos_excluidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='encaminhamento',
            index=models.Index(fields=['atendimento', 'data'], name='encaminhame_atendim_f6b932_idx'),
        ),
        migrations.AddIndex(
            model_name='encaminhamento',
            index=models.Index(fields=['secretaria_destino'], name='encaminhame_secreta_3f147d_idx'),
        ),
        migrations.AddIndex(
            model_name='encaminhamento',
            index=models.Index(fields=['criado_em'], name='encaminhame_criado__3a222c_idx'),
        ),
    ]
