services:
  - type: web
    name: sap-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --no-input
    startCommand: python manage.py migrate && gunicorn config.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: JWT_COOKIE_SAMESITE
        value: None
      - key: CSRF_COOKIE_SAMESITE
        value: None
      - key: JWT_COOKIE_SECURE
        value: "True"
      - key: CSRF_COOKIE_SECURE
        value: "True"
      - key: FRONTEND_URL
        sync: false
      - key: BACKEND_URL
        sync: false
      - key: EMAIL_BACKEND
        value: anymail.backends.resend.EmailBackend
      - key: DEFAULT_FROM_EMAIL
        sync: false
      - key: RESEND_API_KEY
        sync: false
