# Generated by Django 5.2.14 on 2026-05-18 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0001_initial'),
        ('usuarios', '0002_alter_usuario_groups_alter_usuario_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='gabinete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='assinaturas.gabinete'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_platform_admin',
            field=models.BooleanField(default=False),
        ),
    ]
