# Generated by Django 5.2.14 on 2026-05-22 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0004_gabinete_assinatura_cargo_gabinete_assinatura_nome_and_more'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_entidade', models.CharField(choices=[('pessoa', 'Pessoa'), ('atendimento', 'Atendimento'), ('encaminhamento', 'Encaminhamento'), ('oficio', 'Ofício')], max_length=30)),
                ('objeto_id', models.PositiveIntegerField()),
                ('arquivo', models.FileField(upload_to='anexos/%Y/%m/')),
                ('nome_original', models.CharField(blank=True, max_length=255)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('gabinete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='assinaturas.gabinete')),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['gabinete', 'tipo_entidade', 'objeto_id'], name='core_anexo_gabinet_40135e_idx'), models.Index(fields=['criado_em'], name='core_anexo_criado__59de17_idx')],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_entidade', models.CharField(choices=[('pessoa', 'Pessoa'), ('atendimento', 'Atendimento'), ('encaminhamento', 'Encaminhamento'), ('oficio', 'Ofício')], max_length=30)),
                ('objeto_id', models.PositiveIntegerField()),
                ('texto', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('gabinete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='assinaturas.gabinete')),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['gabinete', 'tipo_entidade', 'objeto_id'], name='core_coment_gabinet_d52b43_idx'), models.Index(fields=['criado_em'], name='core_coment_criado__3a88b3_idx')],
            },
        ),
    ]
