# Generated by Django 5.2.8 on 2026-06-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_anexo_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Criado'), ('update', 'Atualizado'), ('delete', 'Excluído'), ('login', 'Login'), ('logout', 'Logout'), ('export', 'Exportação'), ('download', 'Download')], max_length=20),
        ),
    ]
