# Generated by Django 5.2.14 on 2026-05-18 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0001_initial'),
        ('atendimentos', '0003_atendimento_quem_atendeu_remove_atendido_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='gabinete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos', to='assinaturas.gabinete'),
        ),
    ]
