# Generated by Django 5.2.14 on 2026-05-19 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0004_atendimento_gabinete'),
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='pessoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos', to='pessoas.pessoaatendida'),
        ),
    ]
