# Generated by Django 5.2.14 on 2026-05-22 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0004_gabinete_assinatura_cargo_gabinete_assinatura_nome_and_more'),
        ('atendimentos', '0006_atendimento_status_prazo_retorno_and_more'),
        ('pessoas', '0002_pessoaatendida_ativo_pessoaatendida_excluido_em_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='excluido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='excluido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_excluidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['gabinete', 'status'], name='atendimento_gabinet_2c4d74_idx'),
        ),
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['gabinete', 'prazo_retorno'], name='atendimento_gabinet_0c407a_idx'),
        ),
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['gabinete', 'data_atendimento'], name='atendimento_gabinet_a3f2f8_idx'),
        ),
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['gabinete', 'criado_em'], name='atendimento_gabinet_2b8e85_idx'),
        ),
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['telefone'], name='atendimento_telefon_962264_idx'),
        ),
    ]
