# Generated by Django 5.2.14 on 2026-05-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0007_atendimento_ativo_atendimento_excluido_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='endereco',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
