# Generated by Django 5.2.14 on 2026-05-22 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encaminhamentos', '0002_encaminhamento_ativo_encaminhamento_excluido_em_and_more'),
        ('oficios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='oficio',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='oficio',
            name='excluido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oficio',
            name='excluido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficios_excluidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='oficio',
            index=models.Index(fields=['numero'], name='oficios_ofi_numero_7f6585_idx'),
        ),
        migrations.AddIndex(
            model_name='oficio',
            index=models.Index(fields=['criado_em'], name='oficios_ofi_criado__3e75cd_idx'),
        ),
    ]
