# Generated by Django 5.2.14 on 2026-05-22 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0004_gabinete_assinatura_cargo_gabinete_assinatura_nome_and_more'),
        ('pessoas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoaatendida',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='pessoaatendida',
            name='excluido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pessoaatendida',
            name='excluido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pessoas_excluidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='pessoaatendida',
            index=models.Index(fields=['gabinete', 'nome'], name='pessoas_pes_gabinet_bc9cdc_idx'),
        ),
        migrations.AddIndex(
            model_name='pessoaatendida',
            index=models.Index(fields=['gabinete', 'cpf'], name='pessoas_pes_gabinet_dd4eca_idx'),
        ),
        migrations.AddIndex(
            model_name='pessoaatendida',
            index=models.Index(fields=['telefone'], name='pessoas_pes_telefon_77b462_idx'),
        ),
        migrations.AddIndex(
            model_name='pessoaatendida',
            index=models.Index(fields=['criado_em'], name='pessoas_pes_criado__d05c4e_idx'),
        ),
    ]
