# Generated by Django 5.2.14 on 2026-05-23 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_pessoaatendida_ativo_pessoaatendida_excluido_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoaatendida',
            name='local_trabalho',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
